sudo: required

language: generic

services: 
  - docker

before_install:
  - echo "start creating an image"
  - docker build -t wmc15156/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=ture wmc15156/docker-react-app npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-node"
  env: "DockerNode-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-872144589073"
  bucket_path: "docker-node"
  on:
    branch: master
  access_key_id: $AWS_ACCCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


