version: "3"
services: 
  react:
    build:
      context: . # docker file위치가 어디에 있는지
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes: 
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    stdin_open: true
  tests:
    build:
      contexnt: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /usr/src/app/node_modules
      - ./:/usr/src/app
    command: ["npm" "run" "test"]